### ISSUE TITLE
[META] UI/UX Enhancements

### ISSUE THREAD

**Issue by FinalAngel** [divio/djangocms-text-ckeditor#285]
This Issue collects relevant UI / UX enhancement ideas.

**General**
- [ ] Consider working with: https://github.com/django-ckeditor/django-ckeditor
- [x] Add drag&drop for images/files (#79 #233)
- [ ] Copy plugins inside text editor

**Nested Plugins**
- [x] Add real preview and remove `<img>` (#143, #220, #274)
- [x] Allow resizing of images inside the editor (#68, #120)
- [x] Improve saving/opening mechanism (#152, #249, #271)
- [x] Connect filer with the native CKEditor settings (#307)

**Issues**
- [x] Non-breaking spaces (#131)

**Comment by syaiful6** [comment]
@FinalAngel is "Non-breaking spaces" issue fixed? I am still see that kind of output.
